namespace Docify.LLM.Models;

/// <summary>
/// Represents an AI-generated documentation suggestion for review.
/// </summary>
public record DocumentationSuggestion
{
    /// <summary>
    /// Unique identifier for this suggestion.
    /// </summary>
    public required string Id { get; init; }

    /// <summary>
    /// Reference to the API symbol being documented.
    /// </summary>
    public required string ApiSymbolId { get; init; }

    /// <summary>
    /// Complete XML documentation block generated by the LLM.
    /// </summary>
    public required string GeneratedXml { get; init; }

    /// <summary>
    /// LLM provider used for generation (e.g., "anthropic", "openai").
    /// </summary>
    public required string Provider { get; init; }

    /// <summary>
    /// Specific model version used (e.g., "claude-sonnet-4-5", "gpt-5-nano").
    /// </summary>
    public required string Model { get; init; }

    /// <summary>
    /// Total tokens consumed for this generation.
    /// </summary>
    public required int TokensUsed { get; init; }

    /// <summary>
    /// Estimated cost in USD for this generation.
    /// </summary>
    public required decimal EstimatedCost { get; init; }

    /// <summary>
    /// Timestamp when the suggestion was generated.
    /// </summary>
    public required DateTime Timestamp { get; init; }

    /// <summary>
    /// Current review status of the suggestion.
    /// </summary>
    public required SuggestionStatus Status { get; init; }

    /// <summary>
    /// User-edited version of the XML documentation (null if not edited).
    /// </summary>
    public string? UserEditedXml { get; init; }
}

/// <summary>
/// Review status of a documentation suggestion.
/// </summary>
public enum SuggestionStatus
{
    /// <summary>
    /// Awaiting user review.
    /// </summary>
    Pending,

    /// <summary>
    /// Accepted without modifications.
    /// </summary>
    Accepted,

    /// <summary>
    /// Edited by user before acceptance.
    /// </summary>
    Edited,

    /// <summary>
    /// Regeneration requested.
    /// </summary>
    Regenerated,

    /// <summary>
    /// Skipped by user.
    /// </summary>
    Skipped
}
