blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/vladyslavbardin/docify/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/vladyslavbardin/docify#readme
    about: Read the project documentation and getting started guide
